apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      initContainers:
        - name: generate-initdb-script
          image: {{ .Values.guacamole.image.registry }}/{{ .Values.guacamole.image.repository }}:{{ .Values.guacamole.image.tag }}
          command: ["/bin/sh", "-c"]
          args:
            - "/opt/guacamole/bin/initdb.sh --postgresql > /initdb/initdb.sql"
          volumeMounts:
            - name: initdb
              mountPath: /initdb
        - name: run-initdb-script
          image: docker.io/postgres:14.12
          command: ["/bin/sh", "-c"]
          args:
            - |
              export PGPASSWORD={{ .Values.postgresql.password }} &&
              if psql -h {{ .Values.postgresql.hostname }} -U {{ .Values.postgresql.user }} -d {{ .Values.postgresql.database }} -p {{ .Values.postgresql.port }} -c "\dt" | grep -q guacamole_connection; then
                echo "Table exists, skipping initdb script.";
              else
                psql -h {{ .Values.postgresql.hostname }} -U {{ .Values.postgresql.user }} -d {{ .Values.postgresql.database }} -p {{ .Values.postgresql.port }}  -f /initdb/initdb.sql;
              fi
          volumeMounts:
            - name: initdb
              mountPath: /initdb
      containers:
        - name: guacamole
          image: {{ .Values.guacamole.image.registry }}/{{ .Values.guacamole.image.repository }}:{{ .Values.guacamole.image.tag }}
          env:
            # change priority to just "openid" to hide login form and force redirect to keycloak
            - name: EXTENSION_PRIORITY
              value: postgresql,openid
            - name: OPENID_AUTHORIZATION_ENDPOINT
              value: {{ .Values.oidc.authorizationEndpoint }}
            - name: OPENID_JWKS_ENDPOINT
              value: {{ .Values.oidc.jwksEndpoint }}
            - name: OPENID_ISSUER
              value: {{ .Values.oidc.issuer }}
            - name: OPENID_CLIENT_ID
              value: {{ .Values.oidc.clientId }}
            - name: OPENID_REDIRECT_URI
              value: {{ .Values.oidc.redirectUri }}
            - name: OPENID_USERNAME_CLAIM_TYPE
              value: {{ .Values.oidc.usernameClaimType }}
            - name: POSTGRESQL_DATABASE
              value: {{ .Values.postgresql.database }}
            - name: POSTGRESQL_HOSTNAME
              value: {{ .Values.postgresql.hostname }}
            - name: POSTGRESQL_USER
              value: {{ .Values.postgresql.user }}
            - name: POSTGRESQL_PASSWORD
              value: {{ .Values.postgresql.password }}
            - name: POSTGRESQL_PORT
              value: {{ .Values.postgresql.port | quote }}
            - name: POSTGRESQL_AUTO_CREATE_ACCOUNTS
              value: "true"
            - name: GUACD_HOSTNAME
              value: guacd
            - name: GUACD_PORT
              value: "4822"
            - name: WEBAPP_CONTEXT
              value: ROOT
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
      volumes:
        - name: initdb
          persistentVolumeClaim:
            claimName: guacamole-initdb
